name: landsat-sentinel-fusion

channels:
  - conda-forge
  - defaults

dependencies:
  - shapely=1.6.4=py36_0
  - rasterio=0.36.0=py36_3
  - numpy=1.14.3=py36hcd700cb_1
  - scikit-learn=0.19.1=py36h7aa7ec6_0
  - scipy=1.1.0=py36hfc37229_0
  - geopandas=0.3.0=py36_0
  - pandas=0.23.0=py36_1
  - tqdm=4.23.4=py_0
  - imbalanced-learn=0.3.3=py_0
  - pyproj=1.9.5.1=py36_0
